### ISSUE TITLE
Multiple presses on the 'Word list' link doesn't clear #WordListContainer

### ISSUE THREAD

**Issue by Thaurin** [scytalezero/MemriseUtilities#10]
If courses are exported multiple times by clicking the 'Word list' button multiple times, the word list container just keeps filling up. Suggested fix: use `remove()` to remove the div before adding it.

**Comment by Thaurin** [comment]
The PR should fix this issue.

**Comment by scytalezero** [comment]
Fixed by PR. Thanks again!
