### ISSUE TITLE
No handling of HTTPS

### ISSUE THREAD

**Issue by Kinniken** [scytalezero/MemriseUtilities#3]
Hi,

Thanks for this very handy little tool! Just to let you know that Memrise doesn't seem to allow access over HTTP anymore, at least when logged in, and your tool by default works only over HTTP.

I "fixed" it fine by setting it up to run on the HTTP URL in the Tampermonkey settings and by changing the URL used to load the courses from HTTP to HTTPS (otherwise I had a security error for trying to load HTTP content from within an HTTPS page).

Regards

**Comment by scytalezero** [comment]
Thanks for letting me know, and the helpful analysis! I just pushed an update and tested it on Memrise. It seems to be working now.

**Comment by Kinniken** [comment]
Great to see you could fix it so fast. Cheers.
