### ISSUE TITLE
doesn't work with single level courses on firefox with greasemonkey

### ISSUE THREAD

**Issue by tgaff** [scytalezero/MemriseUtilities#5]
Hi, this seems to work with multi-level courses but when used on single-level courses it doesn't load the words.
The wordlist appears blank on firefox with greasemonkey if the course only has one level.  

For example: https://www.memrise.com/course/462849/everyday-objects-2/

**Comment by scytalezero** [comment]
For courses with a single level you can just select the words and copy them. I'd be happy to accept a PR for this, though.
