### ISSUE TITLE
How can I remove the option for showing the course name and the Level?

### ISSUE THREAD

**Issue by xZoeRx** [scytalezero/MemriseUtilities#7]
Hi. Firstly I wanna thank you for making such a nice script. I want to use your script to import words from Memrise courses to Quizlet but the problem is that there is the course name and the level name next to the  word and its translation. How can I remove it? Can you give me an edited version of the script that does not include the course name and the level after the translations. Thank you!

**Comment by scytalezero** [comment]
I just updated the script. It will now create a second text box under the first that contains only the word and its translation. If that provides what you need, please then close this issue.

**Comment by xZoeRx** [comment]
Thank you very very very much!!!!
