### ISSUE TITLE
Can you add box for words only and box for translations only?

### ISSUE THREAD

**Issue by xZoeRx** [scytalezero/MemriseUtilities#8]
Can you add box for words only and box for translations only?

**Comment by scytalezero** [comment]
I would say that 2 boxes are probably enough - but the bare word and translation box is tab delimited. You can paste that in any spreadsheet viewer and just select the column of Esperanto words or English translations if you want them individually.

**Comment by xZoeRx** [comment]
But what if the definitions are in English and they are long?
https://i.imgur.com/zIlv5EJ.png

**Comment by scytalezero** [comment]
They are tab separated, so if you just copy everything in the second box and paste it into a Google Spreadsheet (for example, Excel should work too) then it will separate things for you: https://imgur.com/a/gHlHS

Hope that helps.
